In [1]:
import pandas as pd

In [2]:
import numpy as np

In [3]:
import matplotlib.pyplot as plt

In [4]:
%matplotlib inline

In [5]:
from sklearn import metrics

In [6]:
from sklearn.neighbors import KNeighborsClassifier

In [7]:
from sklearn.linear_model import LogisticRegression

In [8]:
from sklearn.model_selection import train_test_split

In [9]:
df = pd.read_csv('portals.csv')

In [10]:
print(df)

                         name  \
0                   a2gov_org
1    acikveri-sahinbey-bel-tr
2            africa_open_data
3     ajuntament-de-tarragona
4       ajuntament-de-terassa
..                        ...
597  portal-dados-urbanos-uff
598           open-data-nepal
599                   stat-tj
600                dadosjusbr
601       bratislava-opendata

                                                 title  \
0                                  Ann Arbor, Michigan
1                      Açık Veri Portali - Test Yayını
2                                     Africa Open Data
3                                  Open Data Tarragona
4                                    Open Data Terassa
..                                                 ...
597  Portal de Dados Urbanos PPGAU UFF - Open data ...
598                                    Open Data Nepal
599  Agency on Statistics under President of the Re...
600                                         DadosJusBR
601                        Bratislava Open Data Portal

                                                   url  \
0    http://www.a2gov.org/services/data/Pages/defau...
1              http://acikveri.sahinbey.bel.tr/dataset
2                           http://africaopendata.org/
3                       http://opendata.tarragona.cat/
4                        http://opendata.terrassa.cat/
..                                                 ...
597                  https://portaldados.ppgau.uff.br/
598                         https://opendatanepal.com/
599                             https://www.stat.tj/en
600                            https://dadosjusbr.org/
601                     https://opendata.bratislava.sk

                                                author  \
0                                    City of Ann Arbor
1                                             pinardag
2                                     Africa Open Data
3                              Ajuntament de Tarragona
4                                Ajuntament de Terassa
..                                                 ...
597                              Plano C and PPGAU-UFF
598                               Open Knowledge Nepal
599  The Statistical Agency under President of the ...
600  Instituto Federal de Alagoas (IFAL) in partner...
601  Magistrát hlavného mesta Slovenskej republiky ...

                                             publisher      issued  \
0                                    City of Ann Arbor         NaN
1                                  SahinBey Belediyesi  31/01/2015
2                                     Africa Open Data         NaN
3                              Ajuntament de Tarragona         NaN
4                                Ajuntament de Terassa         NaN
..                                                 ...         ...
597                    Universidade Federal Fluminense  2022-01-03
598                               Open Knowledge Nepal  2018-03-03
599  The Statistical Agency under President of the ...         NaN
600                       Instituto Federal de Alagoas  2018-12-31
601                             The city of Bratislava         NaN

    publisher_classification  \
0                        NaN
1                 Government
2                        NaN
3                 Government
4                 Government
..                       ...
597               Government
598                Community
599               Government
600                Community
601               Government

                                           description  \
0          City of Ann Arbor's Open Data Catalog (USA)
1        The first official open data portal of Turkey
2    Africa's largest central repository for Govern...
3                                  Open Data Tarragona
4                                    Open Data Terassa
..                                                 ...
597  Open data portal customized for urbanism and u...
598  A civil society initiative to make Nepal’s dat...
599  The information in the Statistical Agency is p...
600  The portal consumes or scrapes data from sever...
601  Open data is information or data that is freel...

                         tags        license_id  ...                 place  \
0           ctic unitedstates               NaN  ...   Ann Arbor, Michigan
1             turkey national           Unknown  ...      Gaziantep,Turkey
2                 ckan africa               NaN  ...                Africa
3                  city spain               NaN  ...             Tarragona
4                  city spain               NaN  ...               Terrasa
..                        ...               ...  ...                   ...
597  brazil,academic,urbanism                cc  ...            RJ, Brazil
598                ckan nepal             cc-by  ...      Kathmandu, Nepal
599     tajikistan statistics  Other (Not Open)  ...            Tajikistan
600          brazil judiciary             cc-by  ...                Brazil
601       bratislava slovakia               NaN  ...  Bratislava, Slovakia

                   location country  language  status  \
0    42.2681569,-83.7312291      US        en  active
1      37.0587715,37.380137      TR        tr  active
2      2.0000003,15.9999997      AF        en  active
3           41.1157, 1.2496      ES  ca es en  active
4           41.5611, 2.0081      ES     es en  active
..                      ...     ...       ...     ...
597    -22.90501, -43.13053      BR        pt  active
598         27.7097,85.3209      NP        en  active
599   38.5754817,68.7900625      TJ        en  active
600     15.74706, -47.89593      BR        pt  active
601      48.14409, 17.10971      SK        sk  active

              metadatacreated                       generator  \
0    2011-06-27T18:12:57.439Z                             NaN
1                         NaN                             NaN
2    2013-03-15T07:17:26.251Z                     CKAN: 2.1.3
3                         NaN                             NaN
4                         NaN                             NaN
..                        ...                             ...
597      2022-06-19T23:58:00Z                            CKAN
598         2022-07-01T08:37Z                            ckan
599       2022-07-17T16:49:49                             NaN
600      2022-07-24T22:38:06Z  Custom/in-house implementation
601      2023-05-04T14:22:56Z  Custom/in-house implementation

                               api_endpoint                        api_type  \
0                                       NaN                             NaN
1                                       NaN                             NaN
2            http://africaopendata.org/api/                             NaN
3                                       NaN                             NaN
4                                       NaN                             NaN
..                                      ...                             ...
597  https://portaldados.ppgau.uff.br/api/3                        CKAN API
598           https://opendatanepal.com/api                        CKAN API
599                                     NaN                             NaN
600             https://api.dadosjusbr.org/  Custom/in-house implementation
601      https://opendata.bratislava.sk/api  Custom/in-house implementation

    full_metadata_download
0                      NaN
1                      NaN
2                      NaN
3                      NaN
4                      NaN
..                     ...
597                    NaN
598                    NaN
599                    NaN
600                    NaN
601                    NaN

[602 rows x 22 columns]

In [11]:
df.isnull()

,name,title,url,author,publisher,issued,publisher_classification,description,tags,license_id,...,place,location,country,language,status,metadatacreated,generator,api_endpoint,api_type,full_metadata_download
0,False,False,False,False,False,True,True,False,False,True,...,False,False,False,False,False,False,True,True,True,True
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,True,True,True,True,True
2,False,False,False,False,False,True,True,False,False,True,...,False,False,False,False,False,False,False,False,True,True
3,False,False,False,False,False,True,False,False,False,True,...,False,False,False,False,False,True,True,True,True,True
4,False,False,False,False,False,True,False,False,False,True,...,False,False,False,False,False,True,True,True,True,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
597,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,True
598,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,True
599,False,False,False,False,False,True,False,False,False,False,...,False,False,False,False,False,False,True,True,True,True
600,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,True
601,False,False,False,False,False,True,False,False,False,True,...,False,False,False,False,False,False,False,False,False,True

In [12]:
df.describe()

,name,title,url,author,publisher,issued,publisher_classification,description,tags,license_id,...,place,location,country,language,status,metadatacreated,generator,api_endpoint,api_type,full_metadata_download
count,602,602,602,537,541,97,220,553,529,289,...,600,579,587,593,602,460,95,45,78,15
unique,598,596,598,495,504,87,7,549,276,43,...,495,492,129,77,3,424,24,45,8,15
top,state_of_washington,Washington,http://dadosabertos.senado.gov.br/,African Development Bank Group,African Development Bank Group,27/08/2015,Government,Public Open Data of the State of Washington,canada,cc-by,...,Italy,"0,0",US,en,active,2018-09-12T10:58:52Z,CKAN,http://africaopendata.org/api/,CKAN API,https://data.qld.gov.au/api/3/action/current_p...
freq,4,4,2,21,22,2,191,2,45,48,...,9,10,100,271,587,30,37,1,38,1

In [13]:
size = df.size

In [14]:
shape = df.shape

In [15]:
df_ndim = df.ndim

In [16]:
series_ndim = df["name"].ndim

In [17]:
print("size = {}\nShape = {}\nShape[0] x Shape[1] = {}".format(size, shape, shape[0]*shape[1]))

size = 13244
Shape = (602, 22)
Shape[0] x Shape[1] = 13244

In [18]:
print("ndim of dataframe = {}\nndim of series = {}".format(df_ndim, series_ndim))

ndim of dataframe = 2
ndim of series = 1

In [19]:
dataTypeSeries = df.dtypes

In [20]:
print("data type of each column of Dataframe is")
print(dataTypeSeries)

data type of each column of Dataframe is
name                        object
title                       object
url                         object
author                      object
publisher                   object
issued                      object
publisher_classification    object
description                 object
tags                        object
license_id                  object
license_url                 object
license_notes               object
place                       object
location                    object
country                     object
language                    object
status                      object
metadatacreated             object
generator                   object
api_endpoint                object
api_type                    object
full_metadata_download      object
dtype: object

In [22]:
dummies = pd.get_dummies(df.author)

In [23]:
merged = pd.concat([df,dummies], axis='columns');

In [24]:
merged.drop(['author'], axis='columns')

,name,title,url,publisher,issued,publisher_classification,description,tags,license_id,license_url,...,Wyre Council,Xunta de Galicia,data.go.kr,data.gov.sk,e-Government Center,http://g0vhk.io,http://garagelab.tumblr.com/,pinardag,regione sardegna,Örebro Kommun
0,a2gov_org,"Ann Arbor, Michigan",http://www.a2gov.org/services/data/Pages/defau...,City of Ann Arbor,NaN,NaN,City of Ann Arbor's Open Data Catalog (USA),ctic unitedstates,NaN,NaN,...,0,0,0,0,0,0,0,0,0,0
1,acikveri-sahinbey-bel-tr,Açık Veri Portali - Test Yayını,http://acikveri.sahinbey.bel.tr/dataset,SahinBey Belediyesi,31/01/2015,Government,The first official open data portal of Turkey,turkey national,Unknown,NaN,...,0,0,0,0,0,0,0,1,0,0
2,africa_open_data,Africa Open Data,http://africaopendata.org/,Africa Open Data,NaN,NaN,Africa's largest central repository for Govern...,ckan africa,NaN,NaN,...,0,0,0,0,0,0,0,0,0,0
3,ajuntament-de-tarragona,Open Data Tarragona,http://opendata.tarragona.cat/,Ajuntament de Tarragona,NaN,Government,Open Data Tarragona,city spain,NaN,NaN,...,0,0,0,0,0,0,0,0,0,0
4,ajuntament-de-terassa,Open Data Terassa,http://opendata.terrassa.cat/,Ajuntament de Terassa,NaN,Government,Open Data Terassa,city spain,NaN,NaN,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
597,portal-dados-urbanos-uff,Portal de Dados Urbanos PPGAU UFF - Open data ...,https://portaldados.ppgau.uff.br/,Universidade Federal Fluminense,2022-01-03,Government,Open data portal customized for urbanism and u...,"brazil,academic,urbanism",cc,NaN,...,0,0,0,0,0,0,0,0,0,0
598,open-data-nepal,Open Data Nepal,https://opendatanepal.com/,Open Knowledge Nepal,2018-03-03,Community,A civil society initiative to make Nepal’s dat...,ckan nepal,cc-by,https://creativecommons.org/licenses/by/4.0/,...,0,0,0,0,0,0,0,0,0,0
599,stat-tj,Agency on Statistics under President of the Re...,https://www.stat.tj/en,The Statistical Agency under President of the ...,NaN,Government,The information in the Statistical Agency is p...,tajikistan statistics,Other (Not Open),NaN,...,0,0,0,0,0,0,0,0,0,0
600,dadosjusbr,DadosJusBR,https://dadosjusbr.org/,Instituto Federal de Alagoas,2018-12-31,Community,The portal consumes or scrapes data from sever...,brazil judiciary,cc-by,NaN,...,0,0,0,0,0,0,0,0,0,0
601,bratislava-opendata,Bratislava Open Data Portal,https://opendata.bratislava.sk,The city of Bratislava,NaN,Government,Open data is information or data that is freel...,bratislava slovakia,NaN,NaN,...,0,0,0,0,0,0,0,0,0,0

In [25]:
print(merged)

                         name  \
0                   a2gov_org
1    acikveri-sahinbey-bel-tr
2            africa_open_data
3     ajuntament-de-tarragona
4       ajuntament-de-terassa
..                        ...
597  portal-dados-urbanos-uff
598           open-data-nepal
599                   stat-tj
600                dadosjusbr
601       bratislava-opendata

                                                 title  \
0                                  Ann Arbor, Michigan
1                      Açık Veri Portali - Test Yayını
2                                     Africa Open Data
3                                  Open Data Tarragona
4                                    Open Data Terassa
..                                                 ...
597  Portal de Dados Urbanos PPGAU UFF - Open data ...
598                                    Open Data Nepal
599  Agency on Statistics under President of the Re...
600                                         DadosJusBR
601                        Bratislava Open Data Portal

                                                   url  \
0    http://www.a2gov.org/services/data/Pages/defau...
1              http://acikveri.sahinbey.bel.tr/dataset
2                           http://africaopendata.org/
3                       http://opendata.tarragona.cat/
4                        http://opendata.terrassa.cat/
..                                                 ...
597                  https://portaldados.ppgau.uff.br/
598                         https://opendatanepal.com/
599                             https://www.stat.tj/en
600                            https://dadosjusbr.org/
601                     https://opendata.bratislava.sk

                                                author  \
0                                    City of Ann Arbor
1                                             pinardag
2                                     Africa Open Data
3                              Ajuntament de Tarragona
4                                Ajuntament de Terassa
..                                                 ...
597                              Plano C and PPGAU-UFF
598                               Open Knowledge Nepal
599  The Statistical Agency under President of the ...
600  Instituto Federal de Alagoas (IFAL) in partner...
601  Magistrát hlavného mesta Slovenskej republiky ...

                                             publisher      issued  \
0                                    City of Ann Arbor         NaN
1                                  SahinBey Belediyesi  31/01/2015
2                                     Africa Open Data         NaN
3                              Ajuntament de Tarragona         NaN
4                                Ajuntament de Terassa         NaN
..                                                 ...         ...
597                    Universidade Federal Fluminense  2022-01-03
598                               Open Knowledge Nepal  2018-03-03
599  The Statistical Agency under President of the ...         NaN
600                       Instituto Federal de Alagoas  2018-12-31
601                             The city of Bratislava         NaN

    publisher_classification  \
0                        NaN
1                 Government
2                        NaN
3                 Government
4                 Government
..                       ...
597               Government
598                Community
599               Government
600                Community
601               Government

                                           description  \
0          City of Ann Arbor's Open Data Catalog (USA)
1        The first official open data portal of Turkey
2    Africa's largest central repository for Govern...
3                                  Open Data Tarragona
4                                    Open Data Terassa
..                                                 ...
597  Open data portal customized for urbanism and u...
598  A civil society initiative to make Nepal’s dat...
599  The information in the Statistical Agency is p...
600  The portal consumes or scrapes data from sever...
601  Open data is information or data that is freel...

                         tags        license_id  ... Wyre Council  \
0           ctic unitedstates               NaN  ...            0
1             turkey national           Unknown  ...            0
2                 ckan africa               NaN  ...            0
3                  city spain               NaN  ...            0
4                  city spain               NaN  ...            0
..                        ...               ...  ...          ...
597  brazil,academic,urbanism                cc  ...            0
598                ckan nepal             cc-by  ...            0
599     tajikistan statistics  Other (Not Open)  ...            0
600          brazil judiciary             cc-by  ...            0
601       bratislava slovakia               NaN  ...            0

    Xunta de Galicia data.go.kr data.gov.sk e-Government Center  \
0                  0          0           0                   0
1                  0          0           0                   0
2                  0          0           0                   0
3                  0          0           0                   0
4                  0          0           0                   0
..               ...        ...         ...                 ...
597                0          0           0                   0
598                0          0           0                   0
599                0          0           0                   0
600                0          0           0                   0
601                0          0           0                   0

    http://g0vhk.io http://garagelab.tumblr.com/ pinardag regione sardegna  \
0                 0                            0        0                0
1                 0                            0        1                0
2                 0                            0        0                0
3                 0                            0        0                0
4                 0                            0        0                0
..              ...                          ...      ...              ...
597               0                            0        0                0
598               0                            0        0                0
599               0                            0        0                0
600               0                            0        0                0
601               0                            0        0                0

    Örebro Kommun
0               0
1               0
2               0
3               0
4               0
..            ...
597             0
598             0
599             0
600             0
601             0

[602 rows x 517 columns]